{
  "openapi": "3.0.1",
  "info": {
    "title": "商店 API",
    "description": "管理宠物、订单、购买、用户等宠物店业务操作。",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "pet"
    }
  ],
  "paths": {
    "/pets/{id}": {
      "get": {
        "summary": "获取宠物",
        "deprecated": false,
        "description": "根据唯一 ID 返回一只宠物。",
        "operationId": "getPetById",
        "tags": [
          "pet"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "宠物的唯一标识。",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "操作成功",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                },
                "example": {
                  "id": 100,
                  "category": {
                    "id": 101,
                    "name": "dog"
                  },
                  "name": "Luna",
                  "photoUrls": [
                    "https://loremflickr.com/400/400?lock=2557291284045546",
                    "https://loremflickr.com/400/400?lock=1603075073377479"
                  ],
                  "tags": [
                    {
                      "id": 15,
                      "name": "Dalmatian"
                    }
                  ],
                  "status": "available"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "bearer_token": []
          }
        ]
      },
      "put": {
        "summary": "更新宠物",
        "deprecated": false,
        "description": "更新已有宠物的信息。",
        "operationId": "updatePet",
        "tags": [
          "pet"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "宠物的唯一标识。",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "宠物更新成功。",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Pet"
                },
                "example": {
                  "id": 57619952,
                  "category": {
                    "id": 97056790,
                    "name": "Mona Kshlerin"
                  },
                  "name": "doggie",
                  "photoUrls": [
                    "https://loremflickr.com/400/400?lock=190427740691304",
                    "https://loremflickr.com/400/400?lock=5512522463237719",
                    "https://loremflickr.com/400/400?lock=1184069713463914"
                  ],
                  "tags": [
                    {
                      "id": 1230446,
                      "name": "Timmy Schiller"
                    },
                    {
                      "id": 310656,
                      "name": "Ricardo Emard PhD"
                    }
                  ],
                  "status": "pending"
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      },
      "delete": {
        "summary": "删除宠物",
        "deprecated": false,
        "description": "通过唯一 ID 删除宠物。",
        "operationId": "deletePet",
        "tags": [
          "pet"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "宠物的唯一标识。",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "api_key",
            "in": "header",
            "description": "授权所需的 API 密钥（如有）。",
            "required": false,
            "example": "apikey-xxxxx",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "宠物删除成功。",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          },
          "204": {
            "description": "无内容。宠物已被删除且没有返回其他内容。",
            "headers": {}
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      }
    },
    "/pets": {
      "post": {
        "summary": "创建宠物",
        "deprecated": false,
        "description": "向商店添加新宠物。",
        "operationId": "addPet",
        "tags": [
          "pet"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Pet"
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "宠物创建成功。",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer",
                      "description": "宠物唯一标识。"
                    }
                  },
                  "required": [
                    "id"
                  ]
                },
                "example": {
                  "id": 100
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      },
      "get": {
        "summary": "列出宠物",
        "deprecated": false,
        "description": "可用逗号分隔字符串提供多个状态值。",
        "operationId": "findPetsByStatus",
        "tags": [
          "pet"
        ],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "用于筛选宠物状态的值（接受逗号分隔值）。",
            "required": false,
            "example": [
              "available,pending"
            ],
            "schema": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "available",
                  "pending",
                  "sold"
                ],
                "default": "available"
              }
            }
          },
          {
            "name": "tags",
            "in": "query",
            "description": "按标签筛选结果（接受逗号分隔或重复参数）。",
            "required": false,
            "example": [
              "dog,fish"
            ],
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "操作成功",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Pet"
                  }
                },
                "example": [
                  {
                    "id": 15,
                    "category": {
                      "id": 21,
                      "name": "Marcella Weissnat"
                    },
                    "name": "doggie",
                    "photoUrls": [
                      "https://loremflickr.com/400/400?lock=3918785348234384",
                      "https://loremflickr.com/400/400?lock=6202587563304484"
                    ],
                    "tags": [
                      {
                        "id": 47,
                        "name": "Celia Breitenberg"
                      }
                    ],
                    "status": "available"
                  },
                  {
                    "id": 71,
                    "category": {
                      "id": 46,
                      "name": "Amber Boyer"
                    },
                    "name": "doggie",
                    "photoUrls": [
                      "https://loremflickr.com/400/400?lock=2842023516272171"
                    ],
                    "tags": [
                      {
                        "id": 11,
                        "name": "Dr. Victoria Zieme"
                      }
                    ],
                    "status": "pending"
                  },
                  {
                    "id": 40,
                    "category": {
                      "id": 61,
                      "name": "Sheryl Boyer"
                    },
                    "name": "doggie",
                    "photoUrls": [
                      "https://loremflickr.com/400/400?lock=5750598354305884",
                      "https://loremflickr.com/400/400?lock=2063547589454977"
                    ],
                    "tags": [
                      {
                        "id": 78,
                        "name": "Gene Deckow-Lynch"
                      }
                    ],
                    "status": "available"
                  }
                ]
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      }
    },
    "/pets/{petId}/images": {
      "post": {
        "summary": "上传宠物图片",
        "deprecated": false,
        "description": "为指定的宠物上传图片。",
        "operationId": "uploadFile",
        "tags": [
          "pet"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "宠物的唯一标识。",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "petId",
            "in": "path",
            "description": "",
            "required": true,
            "example": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "additionalMetadata": {
                    "description": "Additional data to pass to server",
                    "type": "string",
                    "example": ""
                  },
                  "file": {
                    "description": "File to upload",
                    "type": "string",
                    "format": "binary",
                    "example": ""
                  }
                }
              },
              "examples": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "操作成功",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ApiResponse"
                },
                "example": {
                  "code": 3,
                  "type": "ex dolor",
                  "message": "Pecus carcer cometes credo."
                }
              }
            },
            "headers": {}
          }
        },
        "security": [
          {
            "petstore_auth": [
              "write:pets",
              "read:pets"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "schemas": {
      "Pet": {
        "type": "object",
        "description": "宠物商店中的动物信息。",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "description": "唯一宠物标识。"
          },
          "category": {
            "$ref": "#/components/schemas/Category"
          },
          "name": {
            "type": "string",
            "description": "宠物名称",
            "example": "doggie"
          },
          "photoUrls": {
            "type": "array",
            "description": "宠物图片 URL 列表。",
            "xml": {
              "wrapped": true
            },
            "items": {
              "type": "string",
              "xml": {
                "name": "photoUrl"
              }
            }
          },
          "tags": {
            "type": "array",
            "description": "宠物关联标签。",
            "xml": {
              "wrapped": true
            },
            "items": {
              "$ref": "#/components/schemas/Tag"
            }
          },
          "status": {
            "type": "string",
            "description": "宠物在商店中的状态",
            "enum": [
              "available",
              "pending",
              "sold"
            ]
          }
        },
        "xml": {
          "name": "Pet"
        }
      },
      "Category": {
        "type": "object",
        "description": "宠物所属分类。",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "description": "类别唯一 ID。"
          },
          "name": {
            "type": "string",
            "description": "类别名称。"
          }
        },
        "xml": {
          "name": "Category"
        }
      },
      "ApiResponse": {
        "type": "object",
        "description": "通用 API 响应模型。",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "响应时返回的应用码。"
          },
          "type": {
            "type": "string",
            "description": "响应类型/分类。"
          },
          "message": {
            "type": "string",
            "description": "响应的人类可读信息。"
          }
        }
      },
      "Tag": {
        "type": "object",
        "description": "与宠物关联的标签。",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "description": "标签唯一 ID。"
          },
          "name": {
            "type": "string",
            "description": "标签值。"
          }
        },
        "xml": {
          "name": "Tag"
        }
      }
    },
    "responses": {
      "BadRequest": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/bad-request"
                },
                "title": {
                  "type": "string",
                  "example": "Bad Request"
                },
                "status": {
                  "type": "integer",
                  "example": 400
                },
                "detail": {
                  "type": "string",
                  "example": "The request is invalid or missing required parameters."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/bad-request",
                  "title": "Bad Request",
                  "status": 400,
                  "detail": "The request is invalid or missing required parameters."
                }
              }
            }
          }
        }
      },
      "Unauthorized": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/unauthorized"
                },
                "title": {
                  "type": "string",
                  "example": "Unauthorized"
                },
                "status": {
                  "type": "integer",
                  "example": 401
                },
                "detail": {
                  "type": "string",
                  "example": "You do not have the necessary permissions."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/unauthorized",
                  "title": "Unauthorized",
                  "status": 401,
                  "detail": "You do not have the necessary permissions."
                }
              }
            }
          }
        }
      },
      "Forbidden": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/forbidden"
                },
                "title": {
                  "type": "string",
                  "example": "Forbidden"
                },
                "status": {
                  "type": "integer",
                  "example": 403
                },
                "detail": {
                  "type": "string",
                  "example": "Access is forbidden with the provided credentials."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/forbidden",
                  "title": "Forbidden",
                  "status": 403,
                  "detail": "Access is forbidden with the provided credentials."
                }
              }
            }
          }
        }
      },
      "NotFound": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/not-found"
                },
                "title": {
                  "type": "string",
                  "example": "Not Found"
                },
                "status": {
                  "type": "integer",
                  "example": 404
                },
                "detail": {
                  "type": "string",
                  "example": "The specified resource does not exist."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/not-found",
                  "title": "Not Found",
                  "status": 404,
                  "detail": "The specified resource does not exist."
                }
              }
            }
          }
        }
      },
      "TooManyRequests": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/too-many-requests"
                },
                "title": {
                  "type": "string",
                  "example": "Too Many Requests"
                },
                "status": {
                  "type": "integer",
                  "example": 429
                },
                "detail": {
                  "type": "string",
                  "example": "You have exceeded the rate limit."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/too-many-requests",
                  "title": "Too Many Requests",
                  "status": 429,
                  "detail": "You have exceeded the rate limit."
                }
              }
            }
          }
        }
      },
      "InternalServerError": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/internal-server-error"
                },
                "title": {
                  "type": "string",
                  "example": "Internal Server Error"
                },
                "status": {
                  "type": "integer",
                  "example": 500
                },
                "detail": {
                  "type": "string",
                  "example": "An unexpected error occurred."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/internal-server-error",
                  "title": "Internal Server Error",
                  "status": 500,
                  "detail": "An unexpected error occurred."
                }
              }
            }
          }
        }
      }
    },
    "securitySchemes": {
      "bearer_token": {
        "scheme": "bearer",
        "type": "http"
      },
      "petstore_auth": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "authorizationUrl": "https://petstore.swagger.io/oauth/authorize",
            "scopes": {
              "read:pets": "read your pets",
              "write:pets": "modify pets in your account"
            }
          }
        }
      }
    }
  },
  "servers": [],
  "security": []
}